trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Scripts'
  inputs:
    PathtoPublish: scripts
    ArtifactName: Scripts
